### ISSUE TITLE
Certificate validation fails

### ISSUE THREAD

**Issue by devedse** [lupinelab/kproximate#3]
After a bit of fiddling around I've gotten a few steps further again. The pod is actually reaching my node, however it's throwing the following error:

```
ERROR: kproximate-worker-75dd88574d-mphff2023/09/25 22:15:15 Failed to initialise scaler: Post "https://10.88.20.10:8006/api2/json/access/ticket": tls: failed to verify certificate: x509: certificate signed by unknown authority
```

Is there a way to disable the certificate authority validation?

**Comment by lupinelab** [comment]
Set `pmAllowInsecure: true` in your config to skip tls verification. https://github.com/lupinelab/kproximate/blob/main/chart/kproximate/values.yaml
