### ISSUE TITLE
Kubernetes node-autoscaller

### ISSUE THREAD

**Issue by sergelogvinov** [lupinelab/kproximate#4]
Hello, 
Thank you for your project. I did not try yet, but looks awesome.

I have one question. Did you try to merge this project to the [kubernetes node autoscaller](https://github.com/kubernetes/autoscaler)?

Thanks.

**Comment by lupinelab** [comment]
Hi,

Likewise, I was taking a look at both your proxmox CSI plugin and CCM projects. Both look really interesting.

To answer your question, no I hadn't considered trying to merge kproximate to the kubernetes node autoscaler project. Why do you ask?

**Comment by sergelogvinov** [comment]
I'm just curious. Node autoscale is a very popular repository.
I've had an idea to build a Node autoscale solution based on that framework.
Maybe you know of any potential shortcomings or drawbacks of the Node autoscaler project?

thanks.
