### ISSUE TITLE
Event Hooks and Notifications

### ISSUE THREAD

**Issue by stackblaze** [lupinelab/kproximate#8]
Does kproximate support event hooks for actions like sending notifications to Slack or third-party APIs on scaling events? 

If yes, could you share an implementation example?

**Comment by lupinelab** [comment]
Not currently no

**Comment by lupinelab** [comment]
This isnt something I plan to implement. However, the latest version of kproximate (0.1.5) provides a metrics endpoint which can be used to monitor for events or base notifications of off.
