### ISSUE TITLE
Ability to create new nodes with local storage

### ISSUE THREAD

**Issue by andrewl3wis** [lupinelab/kproximate#9]
Hey!

Got kproximate working, and it's pretty awesome. I have a small three node Proxmox cluster and the one headache I'm dealing with is slow shared storage on my NAS vs local fast nvme. 

Right now if I use a template on a single node local storage it works fine, or if I use the NAS nfs share it works fine across all nodes, however even if I create identical templates on each node, it seems that kproximate only resolves the name for the first template. 

`kproximate-worker-84fd97b88f-bbf762024/02/19 16:45:32 Scale up event failed: 500 can't clone VM to node 'amd3' (VM uses local storage)`

Obviously you could work around this with removing the cluster and making each node it's own singular Proxmox, but it'd be nice to be able to use local storage.

**Comment by strelok899** [comment]
Actually wanted to try kproximate but I use local ssd as vm storage and not shared ceph storage so this helps me to understand that until it resolved I can't use the solution which is pitty as it looks like exactly what I need

**Comment by lupinelab** [comment]
Hi. The newest kproximate release (0.1.6) includes support for using local storage for templates. Please ensure you read the [README](https://github.com/lupinelab/kproximate/blob/main/examples/README.md) for configuration instructions.
